
const layout = [
  [
    {symbol: 'KC_Q', position: [0, 0]},
    {symbol: 'KC_W', position: [1, 0]},
    {symbol: 'KC_E', position: [2, 0]},
    {symbol: 'KC_R', position: [3, 0]},
    {symbol: 'KC_T', position: [4, 0]},
    {symbol: 'KC_Y', position: [5, 0]},
    {symbol: 'KC_U', position: [6, 0]},
    {symbol: 'KC_I', position: [7, 0]},
    {symbol: 'KC_O', position: [8, 0]},
    {symbol: 'KC_P', position: [9, 0]},
  ],
  [
    {symbol: 'KC_A', position: [0, 1]},
    {symbol: 'KC_S', position: [1, 1]},
    {symbol: 'KC_D', position: [2, 1]},
    {symbol: 'KC_F', position: [3, 1]},
    {symbol: 'KC_G', position: [4, 1]},
    {symbol: 'KC_H', position: [5, 1]},
    {symbol: 'KC_J', position: [6, 1]},
    {symbol: 'KC_K', position: [7, 1]},
    {symbol: 'KC_L', position: [8, 1]},
    {symbol: 'KC_SCOLON', position: [9, 1]},
  ],
  [
    {symbol: 'KC_Z', position: [0, 2]},
    {symbol: 'KC_X', position: [1, 2]},
    {symbol: 'KC_C', position: [2, 2]},
    {symbol: 'KC_V', position: [3, 2]},
    {symbol: 'KC_B', position: [4, 2]},
    {symbol: 'KC_N', position: [5, 2]},
    {symbol: 'KC_M', position: [6, 2]},
    {symbol: 'KC_COMMA', position: [7, 2]},
    {symbol: 'KC_DOT', position: [8, 2]},
    {symbol: 'KC_SLASH', position: [9, 2]},
  ],
  [
    {symbol: 'KC_ESCAPE', position: [0, 3]},
    {symbol: 'KC_TAB', position: [1, 3]},
    {symbol: 'KC_LGUI', position: [2, 3]},
    {symbol: 'KC_LSHIFT', position: [3, 3]},
    {symbol: 'KC_BSPACE', position: [4, 3]},
    {symbol: 'KC_LCTRL', position: [5, 3], isThumb: true},
    {symbol: 'KC_LALT', position: [6, 3], isThumb: true},
    {symbol: 'KC_SPACE', position: [7, 3]},
    {symbol: 'KC_FN0', position: [8, 3]},
    {symbol: 'KC_MINUS', position: [9, 3]},
    {symbol: 'KC_QUOTE', position: [10, 3]},
    {symbol: 'KC_ENTER', position: [11, 3]},
  ],
]

export default layout;
