
const rows = [
  [
    {topLabel: 'q', position: [0, 0]},
    {topLabel: 'w', position: [1, 0]},
    {topLabel: 'f', position: [2, 0]},
    {topLabel: 'j', position: [3, 0]},
    {topLabel: 'g', position: [4, 0]},
    {topLabel: 'y', position: [5, 0]},
    {topLabel: 'u', position: [6, 0]},
    {topLabel: 'i', position: [7, 0]},
    {topLabel: 'o', position: [8, 0]},
    {topLabel: 'p', position: [9, 0]},
  ],
  [
    {topLabel: 'a', position: [0, 1]},
    {topLabel: 'r', position: [1, 1]},
    {topLabel: 's', position: [2, 1]},
    {topLabel: 't', position: [3, 1]},
    {topLabel: 'd', position: [4, 1]},
    {topLabel: 'h', position: [5, 1]},
    {topLabel: 'n', position: [6, 1]},
    {topLabel: 'e', position: [7, 1]},
    {topLabel: 'l', position: [8, 1]},
    {topLabel: ':', bottomLabel: ';', position: [9, 1]},
  ],
  [
    {topLabel: 'z', position: [0, 2]},
    {topLabel: 'x', position: [1, 2]},
    {topLabel: 'c', position: [2, 2]},
    {topLabel: 'v', position: [3, 2]},
    {topLabel: 'b', position: [4, 2]},
    {topLabel: 'k', position: [5, 2]},
    {topLabel: 'm', position: [6, 2]},
    {topLabel: '<', bottomLabel: ',', position: [7, 2]},
    {topLabel: '>', bottomLabel: '.', position: [8, 2]},
    {topLabel: '?', bottomLabel: '/', position: [9, 2]},
  ],
  [
    {topLabel: '⎋', position: [0, 3]},
    {topLabel: '⇥', position: [1, 3]},
    {topLabel: 'fn', position: [2, 3]},
    {topLabel: '⌃', position: [3, 3]},
    {topLabel: '⌘', position: [4, 3]},
    {topLabel: '⌫', position: [5, 3], isThumb: true},
    {topLabel: '↩', position: [6, 3], isThumb: true},
    {topLabel: 'spc', position: [7, 3]},
    {topLabel: '⇧', position: [8, 3]},
    {topLabel: '_', bottomLabel: '-', position: [9, 3]},
    {topLabel: '"', bottomLabel: '\'', position: [10, 3]},
    {topLabel: 'fn', position: [11, 3]},
  ],
]

export default rows;
